




.build_ano/mega/src/sketch.ino.cpp : src/sketch.ino
	@mkdir -p .build_ano/mega/src
	@echo [93msrc/sketch.ino[0m
	@/usr/bin/ano preproc --source-dir src  -o $@ $^


all : .build_ano/mega/src/sketch.ino.cpp
	@true

